import type { Request, Response } from "express";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ZodError } from "zod";
import { BadRequestError } from "../lib/errors";
import { errorHandler } from "./errorHandler.middleware";

describe("errorHandler", () => {
	let res: Partial<Response>;

	beforeEach(() => {
		// Mock Express response methods used by the middleware
		res = {
			// Mimic Express method chaining: res.status(...).json(...)
			status: vi.fn().mockReturnThis(),
			// Spy on the JSON response sent to the client
			json: vi.fn(),
		};
	});

	it("should return a 422 response for a Zod validation error", () => {
		// ARRANGE
		// Simulate a validation error generated by Zod
		const zodError = new ZodError([]);

		// ACT
		errorHandler(zodError, {} as Request, res as Response, vi.fn());

		// ASSERT
		expect(res.status).toHaveBeenCalledWith(422);
		expect(res.json).toHaveBeenCalled();
	});

	it("should return the custom status and message for an HttpError", () => {
		// ARRANGE
		const error = new BadRequestError("Invalid request");

		// ACT
		errorHandler(error, {} as Request, res as Response, vi.fn());

		// ASSERT
		expect(res.status).toHaveBeenCalledWith(400);

		expect(res.json).toHaveBeenCalledWith({
			status: 400,
			error: "Invalid request",
		});
	});

	it("should return a generic 500 response in production", () => {
		// ARRANGE
		// Simulate an unexpected application error
		process.env.NODE_ENV = "production";
		const error = new Error("Database crashed");

		// ACT
		errorHandler(error, {} as Request, res as Response, vi.fn());

		// ASSERT
		expect(res.status).toHaveBeenCalledWith(500);

		expect(res.json).toHaveBeenCalledWith({
			status: 500,
			error: "Internal server error",
		});
	});

	it("should return error details in development mode", () => {
		// ARRANGE
		process.env.NODE_ENV = "development";

		const error = new Error("Database crashed");

		// ACT
		errorHandler(error, {} as Request, res as Response, vi.fn());

		// ASSERT
		expect(res.status).toHaveBeenCalledWith(500);

		expect(res.json).toHaveBeenCalledWith(
			expect.objectContaining({
				status: 500,
				error: "Internal server error",
				details: "Database crashed",
			}),
		);
	});
});
