@baseUrl = http://localhost:{{$dotenv PORT}}/api/projects
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4MDM4NTg3MiwiZXhwIjoxNzgwOTkwNjcyfQ.IBCQjZmOblrDPmraNgbcqeUBw3puInxqCVx7dL-Gvk4

###
GET {{baseUrl}}/1
Authorization: Bearer {{token}}


### GET ALL PROJECTS (dashboard)
GET {{baseUrl}}
Authorization: Bearer {{token}}

### POST CREATE / PARTIAL PROJECT
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Week-end à Lisbonne"
}

### POST CREATE / COMPLETE PROJECT
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Coloc rue Pasteur",
    "description": "Dépenses de la coloc",
    "type": "Maison / Coloc",
    "budget": {
        "amount": 1000,
        "alertEnabled": true,
        "limitCriteria": 80
    },
    "participants": [
    { "name": "Ludo" },
    { "name": "Aurore" }
    ]
}

### POST CREATE / INVALID PROJECT
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": ""
}

### GET / 5 PROJECTS
GET {{baseUrl}}
Authorization: Bearer {{token}}

### GET / NEXT PROJECTS
GET {{baseUrl}}?cursor=1
Authorization: Bearer {{token}}